# Site settings
title: Bonza Labs
email: craig.beck@bonzalabs.com
url: http://bonzalabs.com
description: "Custom web application development"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Bonza Labs

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/bonza_labs
  - title: github
    url: https://github.com/bonza-labs

# Build settings
markdown: kramdown
permalink: pretty
